# Generated by Django 5.0.2 on 2025-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='status',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Processing Complete'), ('failed', 'Processing Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Upload Complete'), ('upload_failed', 'Upload Failed')], default='uploading', max_length=20),
        ),
    ]
